version: "3"

services:
  jekyll_custom:
    build: .
    container_name: al-folio-local-website
    command: bash -c "
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --port=7890 --host=0.0.0.0 --livereload --verbose"
    ports:
      - 7890:7890
    volumes:
      - .:/srv/jekyll